name: TNTFill
version: 1.0.0-BETA-SNAPSHOT
main: com.gmail.gogobebe2.tntfill.TNTFill
description: Fill all dispensers in a radius.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  tntfill:
    description: Fill all dispensers in a radius from your inventory evenly.
    aliases: [filltnt]